name-template: 'Release v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Changes
  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: 'Improvements'
    labels:
      - 'enhancement'
  - title: 'Tests'
    labels:
      - 'test'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
      - 'hotfix'
      - 'revert'
  - title: '🧰 Maintenance'
    labels:
      - 'docs'
      - 'chore'
      - 'build'
      - 'ci'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'test'
      - 'hotfix'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/refactor\/.+/'
      - '/perf\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'docs'
    files:
      - '*.md'
      - '*.txt'
      - '*.png'
    branch:
      - '/docs\/.+/'
  - label: 'test'
    branch:
      - '/test\/.+/'
  - label: 'ci'
    files:
      - '*.yml'
    branch:
      - '/ci\/.+/'
  - label: 'revert'
    title:
      - '/revert/i'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
